# Generated by Django 5.1.4 on 2024-12-17 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intake_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CliqueRatioAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('clique_ratio', models.FloatField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake_form.process')),
            ],
        ),
    ]
