# Generated by Django 5.1.4 on 2024-12-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processstep',
            name='description',
        ),
        migrations.AddField(
            model_name='processstep',
            name='name',
            field=models.CharField(default='Unnamed Step', max_length=100),
        ),
        migrations.AlterField(
            model_name='process',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='process',
            name='steps',
            field=models.ManyToManyField(related_name='processes', to='intake_form.processstep'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='contributors',
            field=models.ManyToManyField(related_name='steps', to='intake_form.contributor'),
        ),
    ]
