# Generated by Django 5.1.4 on 2024-12-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_form', '0002_remove_processstep_description_processstep_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processstep',
            name='duration',
        ),
        migrations.AddField(
            model_name='processstep',
            name='duration_unit',
            field=models.CharField(default='seconds', max_length=10),
        ),
        migrations.AddField(
            model_name='processstep',
            name='duration_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='name',
            field=models.CharField(default='Unnamed Contributor', max_length=100),
        ),
        migrations.AlterField(
            model_name='process',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='process',
            name='ideal_duration',
            field=models.DurationField(default='0:00:00'),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(default='Unnamed Process', max_length=100),
        ),
    ]
