# Generated by Django 5.1.4 on 2025-01-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_form', '0003_remove_processstep_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='ideal_duration',
            new_name='tack_time',
        ),
        migrations.AlterField(
            model_name='processstep',
            name='contributors',
            field=models.ManyToManyField(related_name='steps', to='intake_form.contributor', verbose_name='Resources'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='duration_unit',
            field=models.CharField(default='seconds', max_length=10, verbose_name='Flow Time unit'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='duration_value',
            field=models.IntegerField(default=0, verbose_name='Flow Time'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='name',
            field=models.CharField(default='Unnamed Activity', max_length=100),
        ),
    ]
